//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JA.Attack
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "Attack";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Attack";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"JA";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID AttackDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AttackCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID AttackExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AttackCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewAttackExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AttackCommandSetId), 0x0001);
	
		// Package identifier
		public const string AttackPackageId = "f5289f65-761a-4fc5-81b6-efd87c9d9530";
		
		// Editor factory identifier
		public const string AttackEditorFactoryId = "c023d4e4-474b-4609-8c56-e6d127ea55d9";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string AttackModelExplorerToolWindowId = "64507152-d1a4-43d7-bf21-46eb007fa8cb";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace JA.Attack
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string AttackCommandSetId = "12045856-4535-4b10-ac82-9bbe23e6dd7c";
	}
}